spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-token-duration: 1800
  refresh-token-duration: 604800

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    presign-duration: 5m
    read-duration: 5m


resend:
  api-key: ${RESEND_API_KEY}
  from-email: onboarding@resend.dev


cors:
  allowed-origins:
    - http://localhost:5173

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}