spring:
  application:
    name: delivery-platform-api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

geocoding:
  nominatim:
    base-url: https://nominatim.openstreetmap.org
    user-agent: delivery-platform/1.0


mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}


stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  checkout:
    validity-minutes: 60

platform:
  fees:
    const-fee: 50
    fee-rate: 2
    currency: eur

front-end:
  base-url: ${BASE_URL:http://localhost:5173}
  login-url: ${front-end.base-url}/login
  verify-email-url: ${front-end.base-url}/verify-email
  reset-password-url: ${front-end.base-url}/reset-password
