CREATE TABLE payments (
                          id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                          booking_id                  UUID NOT NULL UNIQUE,
                          payer_id                    UUID NOT NULL,
                          stripe_checkout_session_id  VARCHAR(255) NOT NULL UNIQUE,
                          stripe_payment_intent_id    VARCHAR(255) UNIQUE,
                          stripe_charge_id            VARCHAR(255),
                          stripe_refund_id            VARCHAR(255) UNIQUE,
                          amount                      BIGINT NOT NULL CHECK (amount > 0),
                          application_fee_amount      BIGINT NOT NULL CHECK (application_fee_amount >= 0),
                          currency                    VARCHAR(3) NOT NULL DEFAULT 'eur',
                          status                      VARCHAR(20) NOT NULL,
                          created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
                          authorized_at               TIMESTAMPTZ,
                          succeeded_at                TIMESTAMPTZ,
                          canceled_at                 TIMESTAMPTZ,
                          refunded_at                 TIMESTAMPTZ,
                          version                     BIGINT NOT NULL DEFAULT 0,
                          CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(id)                ON DELETE RESTRICT,
                          CONSTRAINT fk_payments_payer   FOREIGN KEY (payer_id)   REFERENCES users(id)            ON DELETE RESTRICT,
                          CONSTRAINT chk_payments_fee    CHECK (application_fee_amount <= amount)
);